CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ─── Fraud Rules: configurable detection rules ──────────────────────────────
CREATE TABLE fraud_rules (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id       VARCHAR(50) NOT NULL,
    rule_code       VARCHAR(100) NOT NULL,
    rule_name       VARCHAR(200) NOT NULL,
    description     TEXT,
    category        VARCHAR(50) NOT NULL,
    severity        VARCHAR(20) NOT NULL DEFAULT 'MEDIUM',
    event_types     TEXT NOT NULL,
    enabled         BOOLEAN NOT NULL DEFAULT TRUE,
    parameters      JSONB DEFAULT '{}',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_fraud_rule UNIQUE (tenant_id, rule_code)
);

-- ─── Fraud Alerts: generated by rule engine or ML models ─────────────────────
CREATE TABLE fraud_alerts (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id       VARCHAR(50) NOT NULL,
    alert_type      VARCHAR(50) NOT NULL,
    severity        VARCHAR(20) NOT NULL DEFAULT 'MEDIUM',
    status          VARCHAR(30) NOT NULL DEFAULT 'OPEN',
    source          VARCHAR(50) NOT NULL DEFAULT 'RULE_ENGINE',
    rule_code       VARCHAR(100),
    customer_id     VARCHAR(100),
    subject_type    VARCHAR(50) NOT NULL,
    subject_id      VARCHAR(100) NOT NULL,
    description     TEXT NOT NULL,
    trigger_event   VARCHAR(100),
    trigger_amount  NUMERIC(19,4),
    risk_score      NUMERIC(5,4),
    model_version   VARCHAR(50),
    explanation     JSONB,
    escalated       BOOLEAN NOT NULL DEFAULT FALSE,
    escalated_to_compliance BOOLEAN NOT NULL DEFAULT FALSE,
    compliance_alert_id UUID,
    assigned_to     VARCHAR(100),
    resolved_by     VARCHAR(100),
    resolved_at     TIMESTAMPTZ,
    resolution      VARCHAR(50),
    resolution_notes TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ─── Velocity Counters: track event frequencies per customer ─────────────────
CREATE TABLE velocity_counters (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id       VARCHAR(50) NOT NULL,
    customer_id     VARCHAR(100) NOT NULL,
    counter_type    VARCHAR(100) NOT NULL,
    window_start    TIMESTAMPTZ NOT NULL,
    window_end      TIMESTAMPTZ NOT NULL,
    count           INTEGER NOT NULL DEFAULT 0,
    total_amount    NUMERIC(19,4) DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_velocity UNIQUE (tenant_id, customer_id, counter_type, window_start)
);

-- ─── Customer Risk Profiles: aggregated risk scoring ─────────────────────────
CREATE TABLE customer_risk_profiles (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id       VARCHAR(50) NOT NULL,
    customer_id     VARCHAR(100) NOT NULL,
    risk_score      NUMERIC(5,4) DEFAULT 0.0,
    risk_level      VARCHAR(20) NOT NULL DEFAULT 'LOW',
    total_alerts     INTEGER DEFAULT 0,
    open_alerts      INTEGER DEFAULT 0,
    confirmed_fraud  INTEGER DEFAULT 0,
    false_positives  INTEGER DEFAULT 0,
    avg_transaction_amount NUMERIC(19,4),
    transaction_count_30d  INTEGER DEFAULT 0,
    last_alert_at   TIMESTAMPTZ,
    last_scored_at  TIMESTAMPTZ,
    factors         JSONB DEFAULT '{}',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_risk_profile UNIQUE (tenant_id, customer_id)
);

-- ─── Fraud Events Log: immutable audit trail of all processed events ─────────
CREATE TABLE fraud_events (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id       VARCHAR(50) NOT NULL,
    event_type      VARCHAR(100) NOT NULL,
    source_service  VARCHAR(100),
    customer_id     VARCHAR(100),
    subject_id      VARCHAR(100),
    amount          NUMERIC(19,4),
    risk_score      NUMERIC(5,4),
    rules_triggered TEXT,
    payload         JSONB,
    processed_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ─── Watchlists: PEP, sanctions, internal blacklist ──────────────────────────
CREATE TABLE watchlist_entries (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id       VARCHAR(50) NOT NULL,
    list_type       VARCHAR(50) NOT NULL,
    entry_type      VARCHAR(50) NOT NULL,
    name            VARCHAR(300),
    national_id     VARCHAR(50),
    phone           VARCHAR(30),
    reason          TEXT,
    source          VARCHAR(200),
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    expires_at      TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ─── Indexes ─────────────────────────────────────────────────────────────────
CREATE INDEX idx_fraud_alerts_tenant ON fraud_alerts(tenant_id);
CREATE INDEX idx_fraud_alerts_status ON fraud_alerts(status);
CREATE INDEX idx_fraud_alerts_customer ON fraud_alerts(customer_id);
CREATE INDEX idx_fraud_alerts_type ON fraud_alerts(alert_type);
CREATE INDEX idx_fraud_alerts_created ON fraud_alerts(created_at DESC);
CREATE INDEX idx_fraud_alerts_severity ON fraud_alerts(severity);

CREATE INDEX idx_velocity_customer ON velocity_counters(tenant_id, customer_id);
CREATE INDEX idx_velocity_window ON velocity_counters(window_end);

CREATE INDEX idx_risk_profile_customer ON customer_risk_profiles(tenant_id, customer_id);
CREATE INDEX idx_risk_profile_level ON customer_risk_profiles(risk_level);
CREATE INDEX idx_risk_profile_score ON customer_risk_profiles(risk_score DESC);

CREATE INDEX idx_fraud_events_tenant ON fraud_events(tenant_id);
CREATE INDEX idx_fraud_events_customer ON fraud_events(customer_id);
CREATE INDEX idx_fraud_events_type ON fraud_events(event_type);
CREATE INDEX idx_fraud_events_processed ON fraud_events(processed_at DESC);

CREATE INDEX idx_watchlist_tenant ON watchlist_entries(tenant_id);
CREATE INDEX idx_watchlist_type ON watchlist_entries(list_type);
CREATE INDEX idx_watchlist_national_id ON watchlist_entries(national_id);
CREATE INDEX idx_watchlist_name ON watchlist_entries(name);
