package com.athena.lms.fraud.enums;

public enum AlertType {
    LARGE_TRANSACTION,
    STRUCTURING,
    HIGH_VELOCITY,
    RAPID_FUND_MOVEMENT,
    APPLICATION_STACKING,
    LOAN_CYCLING,
    EARLY_PAYOFF,
    DORMANT_REACTIVATION,
    KYC_BYPASS,
    OVERDRAFT_ABUSE,
    BNPL_ABUSE,
    PAYMENT_REVERSAL,
    OVERPAYMENT,
    SUSPICIOUS_WRITEOFF,
    WATCHLIST_MATCH,
    ROUND_AMOUNT_PATTERN,
    PROMISE_TO_PAY_GAMING,
    ML_ANOMALY
}
